# This file is managed by Qt Creator, do not edit!

set("CMAKE_EXPORT_COMPILE_COMMANDS" "ON" CACHE "BOOL" "" FORCE)
set("CMAKE_GNUtoMS" "ON" CACHE "BOOL" "" FORCE)
set("CMAKE_SKIP_INSTALL_RPATH" "ON" CACHE "BOOL" "" FORCE)
set("CMAKE_SKIP_RPATH" "ON" CACHE "BOOL" "" FORCE)
set("CMAKE_VERBOSE_MAKEFILE" "ON" CACHE "BOOL" "" FORCE)